# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/cspdcl_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:0000}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# App name
spring.application.name=cspdcl-complaint-system

spring.jpa.open-in-view=false